name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"
env:
  REACT_APP_FIREBASE_API_KEY_STAGING: ${{secrets.REACT_APP_FIREBASE_API_KEY_STAGING}}
  REACT_APP_FIREBASE_API_KEY_PROD: ${{secrets.REACT_APP_FIREBASE_API_KEY_STAGING}}
  REACT_APP_CLIENT_API_TOKEN_STAGING: ${{secrets.REACT_APP_CLIENT_API_TOKEN_STAGING}}
  REACT_APP_CLIENT_API_TOKEN_PROD: ${{secrets.REACT_APP_CLIENT_API_TOKEN_PROD}}
  CI: ${{}}
  REACT_APP_NODE_ENVIRONMENT: production

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: your-Firebase-project-ID
          channelId: live